{
 "title": "Pizza Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "HTTP Requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_per_minute_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "auth_attempts_per_minute_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percentage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas Sold/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "pizzas_sold_per_minute_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue/Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pizza_revenue_per_minute_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "pizza_revenue_per_minute_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Creation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "pizza_creation_failures_per_minute_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Endpoint Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "endpoint_latency_ms_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_creation_latency_ms_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}